#默认使用配置，@activatedProperties@为激活的配置
spring:
  profiles:
    active: @activatedProperties@
  kafka:
    bootstrap-servers: uat-datacenter2:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.ywj.entity.po
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.ywj.dao : debug
server:
  port: 8081
---

#开发配置
spring:
  profiles: local
  datasource:
    druid:
      url: jdbc:mysql://119.29.186.198:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      #url: jdbc:mysql://localhost:3306/test
      username: root
      password: Hushuo2020!@test
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

EsClient:
  cluster:
    name: hs-datacenter-es
  client:
    transport:
      nodeList: uat-datacenter1,uat-datacenter2,uat-datacenter3
      port: 9300
#jasypt:
#  encryptor:
#    password: yangwj

---
#开发配置
spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      #url: jdbc:mysql://localhost:3306/test
      username: root
      password: yang156122
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

EsClient:
  cluster:
    name: hs-datacenter-es
  client:
    transport:
      nodeList: uat-datacenter1,uat-datacenter2,uat-datacenter3
      port: 9300

---
#开发配置
spring:
  profiles: test
  datasource:
    druid:
      url: jdbc:mysql://182.254.171.30:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      #url: jdbc:mysql://localhost:3306/test
      username: dev_admin
      password: 0zepQKBLTYq67Hu
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host:
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

EsClient:
  cluster:
    name: hs-datacenter-es
  client:
    transport:
      nodeList: uat-datacenter1,uat-datacenter2,uat-datacenter3
      port: 9300

---
#开发配置
spring:
  profiles: prod
  datasource:
    druid:
      url: jdbc:mysql://172.16.0.102:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
      #url: jdbc:mysql://localhost:3306/test
      username: admin
      password: sunlands_im
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host:
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

EsClient:
  cluster:
    name: hs-datacenter-es
  client:
    transport:
      nodeList: uat-datacenter1,uat-datacenter2,uat-datacenter3
      port: 9300